# build step
FROM node:16.13.2-alpine as build
WORKDIR /usr/app
COPY src/package.json ./
RUN npm install
COPY src ./
RUN npm run build

# release step
FROM nginx:1.21.5-alpine as release
COPY --from=build /usr/app/build /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]