version: "3"

services:
  backend:
    container_name: backend
    entrypoint: ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
    # entrypoint: ["tail", "-f", "/dev/null"]
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/usr/app/src
      - ./backend/tests:/usr/app/tests
    ports:
      - "8000:8000"
      
    