version: "3"

services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/src:/usr/app/src
      - ./backend/tests:/usr/app/tests
    ports:
      - "8000:8000"
      
    